# Generated by Django 3.1.4 on 2021-03-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmation',
            name='yes_no',
            field=models.BooleanField(default=False),
        ),
    ]
