# Generated by Django 3.1.4 on 2021-03-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_confirmation_yes_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phaseno',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('unmatched', 'Unmatched')], default='pending', max_length=1000),
        ),
    ]
