# Generated by Django 3.1.4 on 2021-03-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210314_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='confirmation',
        ),
    ]
