# Generated by Django 3.1.4 on 2021-03-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_payment_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='phaseno',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
