# Generated by Django 3.1.4 on 2021-03-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20210314_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='phoseno',
            new_name='phaseno',
        ),
    ]
