# Generated by Django 3.1.4 on 2021-03-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20210314_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='document',
            field=models.FileField(upload_to='document/'),
        ),
    ]
