# Generated by Django 3.1.4 on 2021-03-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20210314_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('unmatched', 'Unmatched')], default='pending', max_length=1000),
        ),
    ]
