# Generated by Django 3.1.4 on 2021-03-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20210315_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('unmatched', 'Unmatched')], default='pending', max_length=1000),
        ),
    ]
