# Generated by Django 3.1.4 on 2021-03-16 02:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20210315_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=500)),
                ('cost', models.PositiveIntegerField()),
                ('cert_cost', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=5000)),
                ('phone_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '1234567890'. Up to 10 digits allowed.", regex='^\\d{10,10}$')])),
                ('doc', models.FileField(upload_to='document/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_agency_data')),
            ],
            options={
                'verbose_name': 'PrivateAgency',
                'verbose_name_plural': 'PrivateAgencys',
            },
        ),
    ]
