# Generated by Django 3.1.4 on 2021-03-16 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_privateagency'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateagency',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('unmatched', 'Unmatched')], default='pending', max_length=1000),
        ),
        migrations.AlterField(
            model_name='privateagency',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.grampanchayat', verbose_name='user_agency_data'),
        ),
    ]
