# Generated by Django 3.1.4 on 2021-03-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20210316_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servilenceaudit',
            options={'verbose_name': 'ServilenceAudit', 'verbose_name_plural': 'ServilenceAudits'},
        ),
        migrations.AddField(
            model_name='servilenceaudit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('unmatched', 'Unmatched')], default='pending', max_length=1000),
        ),
        migrations.AlterField(
            model_name='servilencepayment',
            name='remark',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='servilencepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('unmatched', 'Unmatched')], default='pending', max_length=1000),
        ),
    ]
